FROM node:20-alpine

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@10.15.0 --activate

ENV PNPM_STORE_DIR=/pnpm/store

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --no-frozen-lockfile

COPY . .

EXPOSE 4200

# Le "ng serve" est lancé depuis docker-compose.dev.yml :
# "pnpm run start" via docker-compose